title = 'Jason Laumeister'
baseURL = 'https://jasonlaumeister.com'

# if Copyright not set, then title is used
Copyright = 'Jason Laumeister'

languageCode = 'en-us'
preserveTaxonomyNames = true

theme = 'ananke'
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
#resourceDir = "../resources"

SectionPagesMenu = "main"
pagination.pagerSize = 9

googleAnalytics = 'UA-107711386-1'
enableRobotsTXT = true

DefaultContentLanguage = "en"
#[languages]
#    [languages.en]
#        title = "Ananke"
#        weight = 1
#        contentDir = "content/en"
#        # languageDirection = 'rtl' for Right-To-Left languages
#    [languages.fr]
#        title = "Ananke Fr"
#        weight = 2
#        contentDir = "content/fr"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    header_image = 'images/wyoming-field-hero.jpg'
    SEOTitle = 'Resume of Jason Laumeister'
    keyword = 'Jason Laumeister, Laumeister, Software Engineering, Engineering Management'
    slogan = 'Engineering and Technology Tamed'
    upstreamAttribution = true

    # Include any custom CSS and/or JS files, url or relative to /static folder
    #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
    custom_css = ['css/shortcodes.css', 'css/main-custom.css']
    # I don't believe that the custom js array is working properly
    #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

    description = 'Engineering and Technology Tamed'
    text_color = ""
    author = "Jason Laumeister"
    favicon = "images/favicon/favicon.ico"
    site_logo = ""
    # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"

    # number of recent posts to show on home page
    recent_posts_number = 3 

# [[params.ananke_socials]]
#     name = "twitter"
#     url = "https://twitter.com/GoHugoIO"#     

[params.ananke.social]
    icons = true # or false to hide icons
    sharetext = true # or true to show share text
    [[params.ananke.social.networks]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/jasonlaumeister"
    [[params.ananke.social.networks]]
        name = "bluesky"
        url = "https://bsky.app/profile/sudosandwich.bsky.social"
    # Add more networks here

[markup.goldmark.renderer]
    # Allow unsafe embed of raw html in MD files. Only OK because we control all content files on this site. 
    unsafe = true 

[caches]
  [caches.images]
    dir = ':cacheDir/images'